function reproduce_figures_combined(analysis_file, volume_model_file, phase_ED, phase_ES)
%REPRODUCE_FIGURES_COMBINED Generates comparative plots of ED vs ES reconstructions.
%
%   Description:
%     VVisualizes the Stroke Volume effect by plotting ED vs ES envelopes
%     signal envelopes at two different cardiac phases. 
%     Calculates the shaded difference area representing the signal range.
%
%   Inputs:
%     analysis_file     - .mat file generated by RUN_reconstruction.
%     volume_model_file - .mat file containing ventricular volume models.
%     phase_ED          - Target phase for End-Diastole (e.g., 0.75).
%     phase_ES          - Target phase for End-Systole (e.g., 0.31).
%
%   Author: Sung-Han Lin (Hank) [cite: 255]

    %% 1. Load Data
    if ~isfile(analysis_file)
        error('Error: Analysis file not found: %s', analysis_file);
    end
    if ~isfile(volume_model_file)
        error('Error: Volume model file not found: %s', volume_model_file);
    end
    
    fprintf('--- Loading Data ---\n');
    load(analysis_file, 'fit_results', 't_ms', 'y_data', 'cardiac_phase');
    % Ensure variable names match your specific volume model file
    load(volume_model_file, 'LV_fitted_02252025', 'RV_fitted_02252025');

    %% 2. Extract Reconstruction Data (Helper Function)
    %  We call the reconstruction function twice to get the raw numbers
    %  without keeping the intermediate figures.
    
    fprintf('--- Reconstructing Phase 1 (ED): %.2f ---\n', phase_ED);
    [x_ed, y_ed, x_meas, y_meas, x_ideal, y_ideal] = get_recon_data(...
        t_ms, y_data, cardiac_phase, ...
        LV_fitted_02252025, RV_fitted_02252025, fit_results, phase_ED);

    fprintf('--- Reconstructing Phase 2 (ES): %.2f ---\n', phase_ES);
    [x_es, y_es, ~, ~, ~, ~] = get_recon_data(...
        t_ms, y_data, cardiac_phase, ...
        LV_fitted_02252025, RV_fitted_02252025, fit_results, phase_ES);

    %% 3. Generate Visualization
    fprintf('--- Creating Combined Plot ---\n');
    
    % Define Figure Dimensions (4:3 Aspect Ratio, Width 1200px)
    fig_width = 1200;
    fig_height = 900; 
    f_combined = figure('Name', 'Combined Phase Reconstruction', ...
                        'Color', 'w', ...
                        'Position', [50, 50, fig_width, fig_height]);
    
    axes_handle = axes(f_combined);
    hold(axes_handle, 'on');
    grid(axes_handle, 'on');

    % --- Define Colors ---
    c_fill    = [0.60 0.80 1.00];   % Light Blue (Shading)
    c_red_fit = [0.85 0.325 0.098]; % Red (Matches analysis total fit)
    c_blue_ed = [0.00 0.45 0.74];   % Standard Blue (ED)
    c_blue_es = [0.00 0.20 0.50];   % Dark Navy Blue (ES) - for contrast
    c_meas    = [0.00 0.00 0.00];   % Black (Measured)

    % --- A. Draw Shaded Difference Area ---
    % Create polygon vertices for fill
    x_fill = [x_ed(:); flipud(x_ed(:))]; 
    y_fill = [y_ed(:); flipud(y_es(:))];
    
    fill(x_fill, y_fill, c_fill, ...
        'FaceAlpha', 0.3, ...
        'EdgeColor', 'none', ...
        'DisplayName', 'Signal Difference (Stroke Volume)');

    % --- B. Draw Measured & Ideal Reference ---
    % Measured Data: Small black dots, thin lines to minimize occlusion
    plot(x_meas, y_meas, 'o', ...
        'Color', c_meas, ...
        'MarkerFaceColor', c_meas, ...
        'MarkerSize', 3, ...
        'LineWidth', 0.5, ...
        'DisplayName', 'Measured Pyruvate');
    
    % Ideal Total Fit: Red dashed line (High visibility)
    plot(x_ideal, y_ideal, '--', ...
        'Color', c_red_fit, ...
        'LineWidth', 2.0, ...
        'DisplayName', 'Ideal Total Fit');

    % --- C. Draw Reconstruction Curves ---
    % ED Phase (High Signal): Solid Blue, fine markers
    plot(x_ed, y_ed, '-o', ...
        'Color', c_blue_ed, ...
        'MarkerFaceColor', c_blue_ed, ...
        'MarkerSize', 3, ...
        'LineWidth', 1.0, ...
        'DisplayName', sprintf('Reconstructed ED (Phase %.2f)', phase_ED));

    % ES Phase (Low Signal): Solid Dark Blue, fine markers
    plot(x_es, y_es, '-o', ...
        'Color', c_blue_es, ...
        'MarkerFaceColor', c_blue_es, ...
        'MarkerSize', 3, ...
        'LineWidth', 1.0, ...
        'DisplayName', sprintf('Reconstructed ES (Phase %.2f)', phase_ES));

    % --- D. Formatting ---
    xlabel('Time (seconds)', 'FontSize', 14, 'FontWeight', 'bold');
    ylabel('Signal Intensity', 'FontSize', 14, 'FontWeight', 'bold');
    title(sprintf('Reconstruction: ED (%.2f) vs ES (%.2f)', phase_ED, phase_ES), ...
          'FontSize', 16, 'FontWeight', 'bold');
      
    legend('show', 'Location', 'northeast', 'FontSize', 12);
    set(gca, 'FontSize', 12, 'LineWidth', 1.2);
    
    % Adjust Axis Limits
    axis tight;
    ylim_current = ylim;
    ylim([ylim_current(1), ylim_current(2) * 1.05]); % Add 5% headroom

    hold off;

    %% 4. Save Output
    [~, name, ~] = fileparts(analysis_file);
    new_filename = sprintf('%s_Compare_ED%.2f_ES%.2f', name, phase_ED, phase_ES);
    
    fprintf('Saving figure: %s.png\n', new_filename);
    exportgraphics(f_combined, [new_filename, '.png'], 'Resolution', 300);
    savefig(f_combined, [new_filename, '.fig']);
    
    fprintf('Done.\n');
end

%% --- Helper Function ---
function [x_recon, y_recon, x_meas, y_meas, x_ideal, y_ideal] = get_recon_data(t_ms, y_data, cardiac_phase, LV, RV, fit_res, target_ph)
% GET_RECON_DATA Runs the base reconstruction function and scrapes data from the figure.
% Note: This relies on 'reconstruct_signal_by_phase_SP' generating a figure with specific tags.

    % Call the existing reconstruction function
    [~, ~, ~, handles, ~] = reconstruct_signal_by_phase_SP(...
        t_ms, y_data, cardiac_phase, LV, RV, fit_res, target_ph);
    
    fig = handles.reconstruction;
    
    % Find line objects in the generated figure
    lines = findobj(fig, 'Type', 'line');
    
    x_recon = []; y_recon = [];
    x_meas = []; y_meas = [];
    x_ideal = []; y_ideal = [];
    
    % Extract data based on DisplayName (Case-insensitive)
    for i = 1:length(lines)
        name = lines(i).DisplayName;
        if contains(name, 'Reconstructed', 'IgnoreCase', true)
            x_recon = lines(i).XData;
            y_recon = lines(i).YData;
        elseif contains(name, 'Measured', 'IgnoreCase', true)
            x_meas = lines(i).XData;
            y_meas = lines(i).YData;
        elseif contains(name, 'Ideal', 'IgnoreCase', true)
            x_ideal = lines(i).XData;
            y_ideal = lines(i).YData;
        end
    end
    
    % Close the temporary figure immediately
    close(fig);
    
    if isempty(x_recon)
        error('Error: Could not extract data. Check variable names in reconstruct_signal_by_phase_SP.');
    end
end